# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "YOUR_PROJECT_NAME-tf-state"
    dynamodb_table = "terraform_table"
    encrypt        = false
    key            = "./terraform.tfstate"
    profile        = "YOUR_PROFILE_NAME"
    region         = "YOUR_AWS_REGION"
  }
}
