# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "${local.common_vars.project_name}-tf-state"
    dynamodb_table = "terraform_table"
    encrypt        = false
    key            = "./terraform.tfstate"
    profile        = local.common_vars.profile
    region         = local.common_vars.region
  }
}
