cluster_name      = "management-cluster"
project_id        = "GCP_PROJECT_ID"
regions = [ "us-east1" ]
region            = "us-east1"
location          = "us-east1-a"
zone              = "us-east1-a"
node_count        = 3
machine_type      = "e2-standard-2"
image_repo_id     = "PROJECT_NAME-repo"
