# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "region" {
  description = "region name"
}
variable "profile" {
  description = "profile name"
}
provider "aws" {
  region  = var.region
  profile = var.profile
}
